services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=klinik
      - DB_USER=postgres
      - DB_PASSWORD=walrus008
      - SECRET_KEY=mysecretkey
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: klinik
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: walrus008
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d klinik"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: